//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/Input/StandardControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @StandardControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @StandardControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""StandardControls"",
    ""maps"": [
        {
            ""name"": ""Gameplay_01"",
            ""id"": ""9a32095c-66b9-4eef-b781-e74168fd83b1"",
            ""actions"": [
                {
                    ""name"": ""Action_01"",
                    ""type"": ""Button"",
                    ""id"": ""dd1b3b2c-1127-47d8-a9a5-033f8295ad88"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_02"",
                    ""type"": ""Button"",
                    ""id"": ""4a18613a-7051-4650-afc4-a19872550731"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_03"",
                    ""type"": ""Button"",
                    ""id"": ""31250cf8-898e-4419-bc83-ed3f76a04447"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_04"",
                    ""type"": ""Button"",
                    ""id"": ""c3028a29-68c8-4e20-8ad6-de1a78c0e848"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_05"",
                    ""type"": ""Button"",
                    ""id"": ""cf018ebd-8c95-448d-8312-7e29f6629eeb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_06"",
                    ""type"": ""Button"",
                    ""id"": ""b64ff153-386e-42ba-9c9d-fc584d805b2b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Action_00"",
                    ""type"": ""Button"",
                    ""id"": ""6c4cc758-5098-442d-b8bd-f9cae9066d3b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4340a3ce-39d0-4946-bc3b-4c5ac3ca8de6"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1a5ad60-6982-4b6c-8372-3d3aca237e12"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5371c53e-5143-4c1e-b78f-084c9cf005fd"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91a92b2b-8fb5-4ceb-b089-76bad7084bda"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""47b63abc-c917-454d-ae92-188574f24b74"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_05"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""99b773bd-a83d-4f6a-8b0b-1a12e447274d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_06"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0fb3c207-ee7c-4c08-9c88-916cc9f20a12"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Action_00"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay_01
        m_Gameplay_01 = asset.FindActionMap("Gameplay_01", throwIfNotFound: true);
        m_Gameplay_01_Action_01 = m_Gameplay_01.FindAction("Action_01", throwIfNotFound: true);
        m_Gameplay_01_Action_02 = m_Gameplay_01.FindAction("Action_02", throwIfNotFound: true);
        m_Gameplay_01_Action_03 = m_Gameplay_01.FindAction("Action_03", throwIfNotFound: true);
        m_Gameplay_01_Action_04 = m_Gameplay_01.FindAction("Action_04", throwIfNotFound: true);
        m_Gameplay_01_Action_05 = m_Gameplay_01.FindAction("Action_05", throwIfNotFound: true);
        m_Gameplay_01_Action_06 = m_Gameplay_01.FindAction("Action_06", throwIfNotFound: true);
        m_Gameplay_01_Action_00 = m_Gameplay_01.FindAction("Action_00", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay_01
    private readonly InputActionMap m_Gameplay_01;
    private List<IGameplay_01Actions> m_Gameplay_01ActionsCallbackInterfaces = new List<IGameplay_01Actions>();
    private readonly InputAction m_Gameplay_01_Action_01;
    private readonly InputAction m_Gameplay_01_Action_02;
    private readonly InputAction m_Gameplay_01_Action_03;
    private readonly InputAction m_Gameplay_01_Action_04;
    private readonly InputAction m_Gameplay_01_Action_05;
    private readonly InputAction m_Gameplay_01_Action_06;
    private readonly InputAction m_Gameplay_01_Action_00;
    public struct Gameplay_01Actions
    {
        private @StandardControls m_Wrapper;
        public Gameplay_01Actions(@StandardControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Action_01 => m_Wrapper.m_Gameplay_01_Action_01;
        public InputAction @Action_02 => m_Wrapper.m_Gameplay_01_Action_02;
        public InputAction @Action_03 => m_Wrapper.m_Gameplay_01_Action_03;
        public InputAction @Action_04 => m_Wrapper.m_Gameplay_01_Action_04;
        public InputAction @Action_05 => m_Wrapper.m_Gameplay_01_Action_05;
        public InputAction @Action_06 => m_Wrapper.m_Gameplay_01_Action_06;
        public InputAction @Action_00 => m_Wrapper.m_Gameplay_01_Action_00;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay_01; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Gameplay_01Actions set) { return set.Get(); }
        public void AddCallbacks(IGameplay_01Actions instance)
        {
            if (instance == null || m_Wrapper.m_Gameplay_01ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Gameplay_01ActionsCallbackInterfaces.Add(instance);
            @Action_01.started += instance.OnAction_01;
            @Action_01.performed += instance.OnAction_01;
            @Action_01.canceled += instance.OnAction_01;
            @Action_02.started += instance.OnAction_02;
            @Action_02.performed += instance.OnAction_02;
            @Action_02.canceled += instance.OnAction_02;
            @Action_03.started += instance.OnAction_03;
            @Action_03.performed += instance.OnAction_03;
            @Action_03.canceled += instance.OnAction_03;
            @Action_04.started += instance.OnAction_04;
            @Action_04.performed += instance.OnAction_04;
            @Action_04.canceled += instance.OnAction_04;
            @Action_05.started += instance.OnAction_05;
            @Action_05.performed += instance.OnAction_05;
            @Action_05.canceled += instance.OnAction_05;
            @Action_06.started += instance.OnAction_06;
            @Action_06.performed += instance.OnAction_06;
            @Action_06.canceled += instance.OnAction_06;
            @Action_00.started += instance.OnAction_00;
            @Action_00.performed += instance.OnAction_00;
            @Action_00.canceled += instance.OnAction_00;
        }

        private void UnregisterCallbacks(IGameplay_01Actions instance)
        {
            @Action_01.started -= instance.OnAction_01;
            @Action_01.performed -= instance.OnAction_01;
            @Action_01.canceled -= instance.OnAction_01;
            @Action_02.started -= instance.OnAction_02;
            @Action_02.performed -= instance.OnAction_02;
            @Action_02.canceled -= instance.OnAction_02;
            @Action_03.started -= instance.OnAction_03;
            @Action_03.performed -= instance.OnAction_03;
            @Action_03.canceled -= instance.OnAction_03;
            @Action_04.started -= instance.OnAction_04;
            @Action_04.performed -= instance.OnAction_04;
            @Action_04.canceled -= instance.OnAction_04;
            @Action_05.started -= instance.OnAction_05;
            @Action_05.performed -= instance.OnAction_05;
            @Action_05.canceled -= instance.OnAction_05;
            @Action_06.started -= instance.OnAction_06;
            @Action_06.performed -= instance.OnAction_06;
            @Action_06.canceled -= instance.OnAction_06;
            @Action_00.started -= instance.OnAction_00;
            @Action_00.performed -= instance.OnAction_00;
            @Action_00.canceled -= instance.OnAction_00;
        }

        public void RemoveCallbacks(IGameplay_01Actions instance)
        {
            if (m_Wrapper.m_Gameplay_01ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGameplay_01Actions instance)
        {
            foreach (var item in m_Wrapper.m_Gameplay_01ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Gameplay_01ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Gameplay_01Actions @Gameplay_01 => new Gameplay_01Actions(this);
    public interface IGameplay_01Actions
    {
        void OnAction_01(InputAction.CallbackContext context);
        void OnAction_02(InputAction.CallbackContext context);
        void OnAction_03(InputAction.CallbackContext context);
        void OnAction_04(InputAction.CallbackContext context);
        void OnAction_05(InputAction.CallbackContext context);
        void OnAction_06(InputAction.CallbackContext context);
        void OnAction_00(InputAction.CallbackContext context);
    }
}
